# Generated by Django 5.1.1 on 2024-09-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aziende',
            fields=[
                ('id_azienda', models.AutoField(primary_key=True, serialize=False)),
                ('azienda', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competenze',
            fields=[
                ('id_competenza', models.AutoField(primary_key=True, serialize=False)),
                ('competenza', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Offerte',
            fields=[
                ('id_offerta', models.AutoField(primary_key=True, serialize=False)),
                ('id_azienda', models.IntegerField()),
                ('titolo', models.CharField(max_length=50)),
                ('descrizione', models.TextField()),
                ('FK_offerte_aziende', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offerte_competenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_offerta', models.IntegerField()),
                ('id_competenza', models.IntegerField()),
                ('FK_competenze', models.CharField(max_length=255)),
                ('FK_offerte', models.CharField(max_length=255)),
            ],
        ),
    ]
