# Generated by Django 5.1.1 on 2024-09-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerte',
            name='FK_offerte_aziende',
        ),
        migrations.RemoveField(
            model_name='offerte_competenze',
            name='FK_competenze',
        ),
        migrations.RemoveField(
            model_name='offerte_competenze',
            name='FK_offerte',
        ),
    ]
