# Generated by Django 5.1.1 on 2024-09-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_remove_offerte_fk_offerte_aziende_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aziende',
            name='password',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
