# Generated by Django 5.1.1 on 2024-09-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_aziende_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerte_competenze',
            name='id_competenza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.competenze'),
        ),
        migrations.AlterField(
            model_name='offerte_competenze',
            name='id_offerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.offerte'),
        ),
    ]
