# Generated by Django 5.1.1 on 2024-09-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0005_aziende_groups_aziende_is_active_aziende_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aziende',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='aziende',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='aziende',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='aziende',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='aziende',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='aziende',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='aziende',
            name='azienda',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aziende',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
