# Generated by Django 5.1.1 on 2024-09-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0006_remove_aziende_groups_remove_aziende_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aziende',
            name='descrizione',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aziende',
            name='mail',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aziende',
            name='telefono',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aziende',
            name='url_img_1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aziende',
            name='url_img_2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aziende',
            name='url_img_3',
            field=models.CharField(default=33, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aziende',
            name='url_logo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerte',
            name='descrizione_breve',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerte',
            name='luogo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competenze',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
